name: Build Lean OpenWrt for ACRH17 Router

on:
  push:
    branches:
    - master
  schedule:
    - cron: 0 20 * * 5

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        target:
          - ipq40xx
    env:
      REPO_URL: https://github.com/coolsnowwolf/lede
      REPO_BRANCH: master
      OPENWRT_DIR: openwrt
      LUCI_APP_CONFIG: lean-luci-app

    steps:
    - name: Save build info
      id: build_info
      run: |
        echo "##[set-output name=UTCTime;]$(date -u "+%Y-%m-%d %H:%M:%S")"
        echo "##[set-output name=ChinaTime;]$(date -u -d"+8 hour" "+%Y-%m-%d %H:%M:%S")"
        echo "##[set-output name=Url;]$(echo $REPO_URL)"
        echo "##[set-output name=Branch;]$(echo $REPO_BRANCH)"

    - name: Checkout Config Source
      uses: actions/checkout@v1

    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        docker rmi `docker images -q`
        # sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d
        sudo -E apt-get -y purge azure-cli ghc* zulu* llvm* firefox google* dotnet* powershell openjdk* mysql* php*
        sudo -E apt-get update
        sudo -E apt full-upgrade -y 
        sudo -E apt install -y ack antlr3 asciidoc autoconf automake autopoint binutils bison build-essential \
        bzip2 ccache cmake cpio curl device-tree-compiler fastjar flex gawk gettext gcc-multilib g++-multilib \
        git gperf haveged help2man intltool libc6-dev-i386 libelf-dev libfuse-dev libglib2.0-dev libgmp3-dev \
        libltdl-dev libmpc-dev libmpfr-dev libncurses5-dev libncursesw5-dev libpython3-dev libreadline-dev \
        libssl-dev libtool lrzsz mkisofs msmtp ninja-build p7zip p7zip-full patch pkgconf python2.7 python3 \
        python3-pyelftools python3-setuptools qemu-utils rsync scons squashfs-tools subversion swig texinfo \
        uglifyjs upx-ucl unzip vim wget xmlto xxd zlib1g-dev
        sudo -E apt-get -y install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch python3 unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs gcc-multilib g++-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler antlr3 gperf wget swig rsync
        sudo -E apt-get -y autoremove --purge
        sudo -E apt-get clean
        df -h

    - name: Clone source code
      run: git clone --depth 1 $REPO_URL -b $REPO_BRANCH $OPENWRT_DIR

    - name: Update Feed Config
      run: cd $OPENWRT_DIR && sed -i 's/#src-git helloworld/src-git helloworld/g' ./feeds.conf.default

    - name: Update Feeds
      run: cd $OPENWRT_DIR && ./scripts/feeds update -a

    - name: Install Feeds
      run: cd $OPENWRT_DIR && ./scripts/feeds install -a

    - name: Costom configure file
      run: |
          [ -e ${{ matrix.target }}.config ] && cat ${{ matrix.target }}.config >> $OPENWRT_DIR/.config
          [ -e $LUCI_APP_CONFIG.config ] && cat $LUCI_APP_CONFIG.config >> $OPENWRT_DIR/.config

    - name: Load defconfig
      run: |
          cd $OPENWRT_DIR
          make defconfig

    - name: Print Config
      run: cat $OPENWRT_DIR/.config

    - name: Make download
      run: |
        cd $OPENWRT_DIR
        make download -j8
        find dl -size -1024c -exec ls -l {} \;
        find dl -size -1024c -exec rm -f {} \;

    - name: Compile firmware
      run: |
        cd $OPENWRT_DIR
        make -j$(nproc) || make -j1 V=s
        echo "======================="
        echo "Space usage:"
        echo "======================="
        df -h
        echo "======================="
        du -h --max-depth=1 ./ --exclude=build_dir --exclude=bin
        du -h --max-depth=1 ./build_dir
        du -h --max-depth=1 ./bin
        ls -la ./bin/targets/

    - name: Assemble artifact
      run: |
          rm -rf ./artifact/
          mkdir -p ./artifact/
          find $OPENWRT_DIR/bin/targets/ -name "*sysupgrade*bin*" | xargs -i mv -f {} ./artifact/
          find $OPENWRT_DIR/bin/targets/ -name "*combined*img*" | xargs -i mv -f {} ./artifact/

    - name: Upload artifact
      uses: actions/upload-artifact@master
      with:
        name: ${{ matrix.target }}
        path: ./artifact/
